development:
  adapter: postgresql
  encoding: unicode
  database: fishies_development
  pool: 5
  username: fishies
  password: fishies

test:
  adapter: postgresql
  encoding: unicode
  database: fishies_test
  pool: 5
  username: fishies
  password: fishies